import { Router } from "express";
import { authRouter } from "./auth.routes.js";
import { usersRouter } from "./users.routes.js";
import { departmentsRouter } from "./departments.routes.js";
import { locationsRouter } from "./locations.routes.js";
import { categoriesRouter } from "./categories.routes.js";
import { prioritiesRouter } from "./priorities.routes.js";
import { statusesRouter } from "./statuses.routes.js";
import { ticketsRouter } from "./tickets.routes.js";
import { assetsRouter } from "./assets.routes.js";
import { knowledgeBaseRouter } from "./knowledgeBase.routes.js";
import { notificationsRouter } from "./notifications.routes.js";
import { reportsRouter } from "./reports.routes.js";
import { auditLogsRouter } from "./auditLogs.routes.js";
import { settingsRouter } from "./settings.routes.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/departments", departmentsRouter);
apiRouter.use("/locations", locationsRouter);
apiRouter.use("/categories", categoriesRouter);
apiRouter.use("/priorities", prioritiesRouter);
apiRouter.use("/statuses", statusesRouter);
apiRouter.use("/tickets", ticketsRouter);
apiRouter.use("/assets", assetsRouter);
apiRouter.use("/knowledge-base", knowledgeBaseRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/audit-logs", auditLogsRouter);
apiRouter.use("/settings", settingsRouter);
